#pragma once

#include <stdio.h>

//clear all errors before retrieving new ones
void glUserClearPrevError();

//print the OpenGL error generated by a specific line
bool glUserLog(const char* func, const char* filepath, unsigned int line);

//assertion 
#define ASSERT(x) if(!(x)){ printf("%s(%d): Assertion Failed\n", __FILE__, __LINE__); __debugbreak(); }
#define GL_USER_ERROR(x) glUserClearPrevError();\
	x; ASSERT(glUserLog(#x, __FILE__, __LINE__));

//print passMsg if cond == true, else print failMsg
#define PRINT_IF_ELSE(cond,passMsg,failMsg)\
	if(cond) printf("%s(%d): %s\n", __FILE__, __LINE__, passMsg);\
	else printf("%s(%d): %s\n", __FILE__, __LINE__, failMsg)