#include "Log.h"
#include <GL/glew.h>

//clear all errors before retrieving new ones
void glUserClearPrevError() {
	while (glGetError());
}

//print the OpenGL error generated by a specific line
bool glUserLog(const char* func, const char* filepath, unsigned int line) {
	while (GLenum err = glGetError()) {
		printf("%s(%d): OpenGL Error(%d): %s\n", filepath, line, err, func);
		return false;
	}
	return true;
}